In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
reliance_data=pd.read_csv("RELIANCE.NS.csv")

In [4]:
reliance_data

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-06-19,1176.654785,1190.461182,1154.436523,1167.922852,1144.442139,7246381
1,2019-06-20,1170.345825,1188.632568,1168.517212,1185.660889,1161.823486,5374424
2,2019-06-21,1184.929443,1184.975220,1166.277100,1169.888672,1146.368408,11618416
3,2019-06-24,1163.168335,1167.099976,1149.407715,1154.253662,1131.047852,5633614
4,2019-06-25,1151.053467,1186.803833,1146.801758,1184.838013,1161.017212,7483449
...,...,...,...,...,...,...,...
1231,2024-06-12,2915.000000,2952.000000,2910.350098,2926.649902,2926.649902,5040871
1232,2024-06-13,2944.000000,2944.500000,2920.199951,2930.500000,2930.500000,4590580
1233,2024-06-14,2940.000000,2959.350098,2914.449951,2955.100098,2955.100098,4078999
1234,2024-06-18,2974.699951,2974.800049,2942.699951,2962.050049,2962.050049,3598383
1235,2024-06-19,2975.000000,2975.000000,2912.000000,2917.300049,2917.300049,4361955

In [5]:
reliance_data.shape

(1236, 7)

In [6]:
reliance_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1236 entries, 0 to 1235
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1236 non-null   object
 1   Open       1236 non-null   float64
 2   High       1236 non-null   float64
 3   Low        1236 non-null   float64
 4   Close      1236 non-null   float64
 5   Adj Close  1236 non-null   float64
 6   Volume     1236 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 67.7+ KB

In [7]:
reliance_data.describe()

,Open,High,Low,Close,Adj Close,Volume
count,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1.236000e+03
mean,2059.432743,2080.746601,2036.740517,2057.936927,2045.117920,1.001400e+07
std,494.250851,496.254350,492.400385,494.528316,499.545467,8.106278e+06
min,837.711609,868.616089,800.635437,808.315857,796.819336,8.528280e+05
25%,1800.541596,1817.386353,1778.701080,1799.826294,1781.447632,5.276993e+06
50%,2184.970947,2204.261719,2162.172851,2183.517212,2170.703003,7.395136e+06
75%,2377.770019,2400.936279,2357.652588,2379.308594,2369.045166,1.145654e+07
max,3011.550049,3029.000000,2974.449951,3020.649902,3020.649902,7.134168e+07

In [8]:
reliance_data.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [12]:
reliance_data.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [11]:
reliance_data['Date']=pd.to_datetime(reliance_data['Date'])

KeyError: 'date'